services:
  mysql001:
    image: "mysql:8.0"
    ports:
      - "13306:3306"
    volumes:
      - ./mysql001/data:/var/lib/mysql
      - ./mysql001/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  mysql002:
    image: "mysql:8.0"
    volumes:
      - ./mysql002/data:/var/lib/mysql
      - ./mysql002/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "23306:3306"
