FROM alpine:3.17
ENV TZ Asia/Shanghai
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8
MAINTAINER lingjian
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk upgrade && \
    apk --no-cache add tzdata ca-certificates bash bash-doc bash-completion vim wget curl net-tools busybox-extras && \
	rm -rf /var/cache/apk/* && \
    cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone
COPY glibc/glibc-2.34-r0.apk /var/cache/apk/
COPY glibc/glibc-bin-2.34-r0.apk /var/cache/apk/
COPY glibc/glibc-i18n-2.34-r0.apk /var/cache/apk/
COPY locale /locale
RUN cd /var/cache/apk/ && \
    mv /etc/nsswitch.conf /etc/nsswitch.conf.bak && \
    apk add --allow-untrusted --force-overwrite glibc-2.34-r0.apk glibc-bin-2.34-r0.apk glibc-i18n-2.34-r0.apk && \
    mv /etc/nsswitch.conf.bak /etc/nsswitch.conf && \
    set -x && cat /locale | xargs -i /usr/glibc-compat/bin/localedef -i {} -f UTF-8 {}.UTF-8
ADD jdk-8u202-linux-x64.tar.gz /opt
ENV JAVA_HOME=/opt/jdk
ENV CLASSPATH=.:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH=$JAVA_HOME/bin:$PATH

